# Generated by Django 4.2.7 on 2024-01-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
    ]
